---
- name: "Installation apache via docker"
  hosts: prod
  become: true
  pre_tasks:
  - name: install EPEL repo
    package: name=epel-release state=present
    when: ansible_distribution == "CentOS"
  - name: download pip script
    get_url:
      url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
      dest: /tmp/get-pip.py
  - name: install python-pip
    command: python2.7 /tmp/get-pip.py
  - name: Install docker python
    pip: name=docker-py
  tasks:
  - name: creation de container apache
    docker_container:
      name: apache
      image: httpd
      ports:
      - "80:80"